/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, chookjhkjhjkhse Tools | Templates
 * and open the template in the editor.
 */
package PokerDeDados;

/**
 *
 * @author ines
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       void setToFalse(Pantalla pantalla) {
        pantalla.King.setVisible(false);
        pantalla.Queen.setVisible(false);
        pantalla.Jack.setVisible(false);
        pantalla.Ten.setVisible(false);
        pantalla.Ace.setVisible(false);
    }

    void rollDice(Pantalla pantalla) {
        int k = 1;
        int q = 2;
        int j = 3;
        int nueve = 4;
        int a = 5;

        new Thread() {
            @Override
            public void run() {
                try {
                    int veces = (int) (Math.random() * 20) + 1;
                    
                    for (int i = 0; i <= veces; i++) {

                        int random = (int) (Math.random() * 5) + 1;
                        
                        switch (random) {
                            case 1:
                                pantalla.King.setVisible(true);
                                break;
                            case 2:
                                pantalla.Queen.setVisible(true);
                                break;
                            case 3:
                                pantalla.Jack.setVisible(true);
                                break;
                            case 4:
                                pantalla.Ten.setVisible(true);
                                break;
                            case 5:
                                pantalla.Ace.setVisible(true);
                                break;
                        }

                        Thread.sleep(300);
                        if (i==veces) {
                        
                        }    
                        else {
                        pantalla.setToFalse(pantalla);}
                    }
                } catch (InterruptedException e) {
                }
            }
        }.start();

    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Queen = new javax.swing.JLabel();
        King = new javax.swing.JLabel();
        Jack = new javax.swing.JLabel();
        Ten = new javax.swing.JLabel();
        Ace = new javax.swing.JLabel();
        bkgrnd = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Queen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/dado2.png"))); // NOI18N
        getContentPane().add(Queen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        King.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/dado.PNG"))); // NOI18N
        getContentPane().add(King, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Jack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/dado3.PNG"))); // NOI18N
        getContentPane().add(Jack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Ten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/dado4.PNG"))); // NOI18N
        getContentPane().add(Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Ace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/dado5.PNG"))); // NOI18N
        getContentPane().add(Ace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        bkgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PokerDeDados/fotos/foto.jpg"))); // NOI18N
        getContentPane().add(bkgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

          /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Pantalla pantalla = new Pantalla();
            pantalla.setVisible(true);
            pantalla.bkgrnd.setVisible(true);
            
            
            pantalla.rollDice(pantalla);
        } //end run method
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ace;
    private javax.swing.JLabel Jack;
    private javax.swing.JLabel King;
    private javax.swing.JLabel Queen;
    private javax.swing.JLabel Ten;
    private javax.swing.JLabel bkgrnd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
